---
title: "Research"
---

## Working Papers and Work in Progress

**The Price of Order: How Violent Crime Weakens Democracy**\
(with [Anderson Frey](https://www.andersonfrey.com/)) — [[pdf](https://www.dropbox.com/scl/fi/5wz1h7qwfp79s80h6l2ey/Cangaco.pdf?rlkey=3fvexenmm0yd46ivq6n1dhzkl&dl=0)]

**Electoral Results Affect Beliefs About the Past: Evidence from Chile**\
(with [Nicolás Ajzenman](https://www.ajzenman.com/) and [Patrício Dominguez](https://sites.google.com/site/pdomingr/)) — [[pdf](https://www.dropbox.com/scl/fi/ptdwwew4a3alv51q22jen/2026_01_version.pdf?rlkey=83aa3vdtyg3wbte6jxmsy1yw8&dl=0)]

**The Autocracy Bandwagon: Political Selection and Autocratic Consolidation**\
(with [Guadalupe Tuñón](https://politics.princeton.edu/people/guadalupe-tunon)) — [email for wp]

**Political Outsiders**\
(in preparation, with [Natalia Garbiras-Diaz](https://www.nataliagarbirasdiaz.com/))

**Ideology First: Physicians in Bolsonaro's Brazil**\
(in preparation, with [Horacio Larreguy](https://sites.google.com/site/hlarreguy/) and [Letícia Nunes](https://www.leticianunes.com/))


## Peer-Reviewed Publications

"[Special Interest Trade-Offs: Campaign Finance Reforms and Religious Influence in Politics in Brazil](https://www.journals.uchicago.edu/doi/10.1086/736804)"\
(with [Melani Cammett](https://cmes.fas.harvard.edu/people/melani-cammett) and [Guadalupe Tuñón](https://politics.princeton.edu/people/guadalupe-tunon)) — *Journal of Politics*, forthcoming. [[pdf accepted manuscript](https://www.dropbox.com/scl/fi/7ywqbe4yng0dbu2svn8b5/cammett_novaes_tunon_JOP_2025.pdf?rlkey=0flojlpeg0ja81b4bl4cjwazb&dl=0)]

"[Bolsonaro's Botched Coup Attempt Exposed Political Fault Lines in the Brazilian Democracy](https://pensamientoeducativo.uc.cl/index.php/rcp/article/view/83138)"\
(with [Diego Werneck Arguelhes](https://scholar.google.com.br/citations?user=h8QfURAAAAAJ&hl=en)) — *Revista de Ciencia Política*, 2024. [[pdf](https://www.dropbox.com/scl/fi/4zgzqgigqb592m6da3yx8/Novaes_Arguelhes_RCP_2024.pdf?rlkey=pm1urift3ngj1xiyfcks80tya&dl=0)]

"[The Violence of Law-and-Order Politics: The Case of Law Enforcement Candidates in Brazil](https://www.cambridge.org/core/journals/american-political-science-review/article/violence-of-lawandorder-politics-the-case-of-law-enforcement-candidates-in-brazil/8B3119D4E66E61B1FC7168FD5231D97B)"\
*American Political Science Review*, 2024, 118(1), 1–20 (lead article). [[pdf](https://www.dropbox.com/scl/fi/ky80j0169rxsk2h6epcqo/Novaes_APSR_2023.pdf?rlkey=pe92ysww33zii37z7s1qhklsd&dl=0)], [[dataverse](https://doi.org/10.7910/DVN/U9ZECG)]\
🏆 Recipient of the 2024 Olavo Brasil Jr. Prize, Brazilian Political Science Association.\
Media: [Blog Faces da Violência](https://facesdaviolencia.blogfolha.uol.com.br/2018/09/29/homicidios-mais-do-que-dobram-em-municipios-que-elegeram-policiais-como-vereadores-diz-estudo-de-instituto-de-pesquisas-em-tolouse-na-franca/), [Época](https://epoca.globo.com/politicos-de-farda-violencia-22940335), [Ponte](https://ponte.org/cidades-que-elegeram-bancadas-da-bala-viram-homicidios-dobrarem/), [Vice](https://www.vice.com/en/article/y3gd95/bolsonaro-has-inspired-more-police-to-run-for-office-in-brazil).

"[Media Manipulation in Young Democracies: Evidence from the 1989 Brazilian Presidential Election](https://journals.sagepub.com/doi/full/10.1177/00104140231169027)"\
(with [Alexsandros Cavgias](https://sites.google.com/view/alexsandroscavgias/home?authuser=0), [Raphael Corbi](https://sites.google.com/site/raphaelcorbi/), and [Luis Meloni](https://www.luismeloni.com/)) — *Comparative Political Studies*, 2024, 67(2). [[pdf](https://www.dropbox.com/s/wkwv5046los72b7/cavgias-et-al-2023-media-manipulation-in-young-democracies-evidence-from-the-1989-brazilian-presidential-election.pdf?dl=0)], [[dataverse](https://doi.org/10.7910/DVN/DEIRCB)]

"[Commodity Shocks and Incumbency Effects](https://www.cambridge.org/core/journals/british-journal-of-political-science/article/commodity-shocks-and-incumbency-effects/6C14B6B7AA39ACD052F7199BCE3B281F)"\
(with [Luis Schiumerini](https://sites.google.com/site/leschiumerini/)) — *British Journal of Political Science*, 2022, 52(4), 1689–1708. [[pdf](https://www.dropbox.com/s/p3xvid032dlpalk/Novaes_schiumerini_BJPS_2021.pdf?dl=0)], [[dataverse](https://doi.org/10.7910/DVN/EV8CBE)]

"[Disloyal Brokers and Weak Parties](https://onlinelibrary.wiley.com/doi/abs/10.1111/ajps.12331)"\
*American Journal of Political Science*, 2018, 62(1), 84–98. [[pdf](https://www.dropbox.com/s/0ynoetsefzca2jz/Novaes_AJPS_2018.pdf?dl=0)], [[dataverse](https://doi.org/10.7910/DVN/BPON3K)]


## Chapters in Edited Volumes

"[The New Left in Broker-Mediated Party Systems](https://www.cambridge.org/core/books/inclusionary-turn-in-latin-american-democracies/9E2C271C6AFB4CBE52BC302082C60230)"\
(with [Thad Dunning](http://www.thaddunning.com/)) — in Kapiszewski, Levitsky and Yashar (eds.) *The Inclusionary Turn in Latin American Democracies*, Cambridge University Press, 2021. [[pdf](https://www.dropbox.com/s/85cltbovc2ko0au/Dunning_Novaes_CUP_2021.pdf?dl=0)]


## Peer-Reviewed Publications, in Portuguese

"[The Effect of Re-election on Health Expenditures: An Analysis of the Reputation-Building Model](http://www.scielo.br/scielo.php?pid=S0101-31572010000100009&script=sci_arttext&tlng=pt)"\
(with [Enlinson Mattos](https://sites.google.com/site/enlinsonmattos/)) — *Brazilian Review of Political Economy* (Revista de Economia Política), 2010, 30(1), 140–158. [[pdf](https://www.dropbox.com/s/wckuoncgb980m85/Novaes_mattos_REP_2010.pdf?dl=0)]

"[Scale Economies in the Supply of Health Services: A Study of São Paulo Municipalities](http://www.anpec.org.br/revista/vol10/vol10n2p357_386.pdf)"\
(with Paulo Arvate, Enlinson Mattos, Veronica Orellano, and Fabiana Rocha) — *Revista ANPEC*, 2009, 10(2), 357–386.


## Non Peer-Reviewed

[Comunicando Incertezas](https://www.insper.edu.br/wp-content/uploads/2021/02/legadodeumapandemia-1.pdf) (with Pedro Burgos), 2021.\
In Machado, Laura Mueller (org.) *Legado de uma Pandemia*. Autografia.

[Mexico Centennial: Limited Independence, Limited Democracy](http://vcro-vm-i004-dev07.berkeley.edu/research/mexicos-centennials-limited-independence-limited-democracy) (with Sinaia Urrusti-Frenk), 2010.\
*Berkeley Review of Latin American Studies*.
